### ISSUE TITLE
Replace Aaron’s picture on the team members page

### ISSUE THREAD

**Issue by akmorrison** [amihaila/wrt-site#56]
change picture and title. Can I be “Electrical noun”? Can the picture be the one I changed my profile pic to?

**Comment by jacobdeery** [comment]
You cannot be "Electrical noun"

**Comment by akmorrison** [comment]
But electrical noun is my job title. How bout electrical $NOUN?

**Comment by akmorrison** [comment]
Electrical designer? To match LinkedIn? Does that satisfy the requirement of killing all whimsy?

**Comment by amihaila** [comment]
pic: dd67626e02ce0bfda422cb0bb476f604f6d84516
title: tbd
