### ISSUE TITLE
Update sponsors list

### ISSUE THREAD

**Issue by jacobdeery** [amihaila/wrt-site#75]
Along with #71, we still need to add:

Airtech - Bronze
Misumi - Bronze (@akmorrison to confirm)
Keysight - Platinum

In addition, SOLIDWORKS needs to move up to Gold tier.

**Comment by jacobdeery** [comment]
Hatch will also move up in tiers once we've received the new sponsorship cheque

**Comment by AidanHa** [comment]
Do we have the logos for these sponsors or can I just pull them from google

Has Hatch gave up the sponsorship cheque?

**Comment by AidanHa** [comment]
This issue can be closed since we updated the sponsorship page zzz
