### ISSUE TITLE
Restrict text width on sponsors page

### ISSUE THREAD

**Issue by amihaila** [amihaila/wrt-site#79]
Can yall add something to restrict the maximum width of text on the sponsors page? (This might also show up on other pages but this one is the main culprit.) The long lines are hard to read and don't look great. Feel free to change the layout if there's something else that looks better and avoids this problem.

Eg.
![Screen Shot 2019-03-12 at 5 43 53 PM](https://user-images.githubusercontent.com/21145713/54245574-8a9d9880-44ee-11e9-977f-c27fc9a9f3fa.png)
![Screen Shot 2019-03-12 at 5 44 03 PM](https://user-images.githubusercontent.com/21145713/54245576-8c675c00-44ee-11e9-94f9-36ad05b6931b.png)

**Comment by jacobdeery** [comment]
Fixed in e478cca
